// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWw6pSm5jdqHkbzeQmBrA3as7QWkQTTlU',
    appId: '1:782408446064:web:cfd855d5685f998e0744b5',
    messagingSenderId: '782408446064',
    projectId: 'authturorial-5a650',
    authDomain: 'authturorial-5a650.firebaseapp.com',
    storageBucket: 'authturorial-5a650.firebasestorage.app',
    measurementId: 'G-GSE0S6L23V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1M4I73vyYVKVjHRpKsIMEv24wilxKYZM',
    appId: '1:782408446064:android:43b4c0f7b730fadb0744b5',
    messagingSenderId: '782408446064',
    projectId: 'authturorial-5a650',
    storageBucket: 'authturorial-5a650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADMlQLHPxJJ29xKDIF4zjgoAk4YEjjOqc',
    appId: '1:782408446064:ios:58be0dca59851a4f0744b5',
    messagingSenderId: '782408446064',
    projectId: 'authturorial-5a650',
    storageBucket: 'authturorial-5a650.firebasestorage.app',
    androidClientId: '782408446064-goe7aseguqmu8ldsboqf9hd205f17ei1.apps.googleusercontent.com',
    iosClientId: '782408446064-6jc3732km2qi5i5jadn6052b4mnmca7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.longtut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADMlQLHPxJJ29xKDIF4zjgoAk4YEjjOqc',
    appId: '1:782408446064:ios:58be0dca59851a4f0744b5',
    messagingSenderId: '782408446064',
    projectId: 'authturorial-5a650',
    storageBucket: 'authturorial-5a650.firebasestorage.app',
    androidClientId: '782408446064-goe7aseguqmu8ldsboqf9hd205f17ei1.apps.googleusercontent.com',
    iosClientId: '782408446064-6jc3732km2qi5i5jadn6052b4mnmca7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.longtut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWw6pSm5jdqHkbzeQmBrA3as7QWkQTTlU',
    appId: '1:782408446064:web:d0b58e0e940507d30744b5',
    messagingSenderId: '782408446064',
    projectId: 'authturorial-5a650',
    authDomain: 'authturorial-5a650.firebaseapp.com',
    storageBucket: 'authturorial-5a650.firebasestorage.app',
    measurementId: 'G-FPWJVYKBK5',
  );

}